import 'package:flutter_app_21/model/Challange.dart';

class Challanges {
  static List<Challange> challangeList = <Challange>[
    Challange(
        challangesName: "Gece Rutini-/Finish",
        description: "Bu mücadelede , daha iyi bir gece uykusu çekmek ve yatma vaktinde daha az stresli hissetmek için bazı ipuçları bulacaksınız.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Günü düşünün,oldukça iyi giden en az bir şeyi yazın.",
          "Rahatlatıcı bir şeyler yapın. Yüz maskesi al , biraz resim yap , banyo yap , rahatlamanıza yardımcı olan şeyler yapın.",
          "Uyumadan en az 1 saat önce telefonunuzdan uzak durun.",
          "Yatmadan önce biraz papatya çayı veya başka bir bitki çayı (kafeinsiz) için",
          "İyi bir uyku ortamına sahip olun. Yatak odasını iyi bir sıcaklıkta tutun ışığı engellemek için karartma perdeleri veya uyku maskesi kullanın.",
          "Durup düşünmek için zaman ayırın",
          "Kokulu mumlar yakın ve rahatlatıcı bir çalma listesi çalın.",
          "Yatmadan önce biraz esneme/yoga yapın.",
          "Bir şükran listesi yazın",
          "Uyumadan önce iyi bir kitap okuyun. Gevşemenize ve daha iyi uyumanıza yardımcı olur",
          "Sonraki günüüzü planlayın. Görevleriniz,kıyafetleriniz,atıştırmalıklarınız...",
          "Sevdiğiniz birine özel bir iyi geceler mesajı gönderin.",
          "Güzel sıcak bir duş alın.",
          "Her gün olduğu gibi dişlerinizi güzelce fırçalayın.",
          "Yatmadan önce dudaklarınızı güzelce nemlendirin",
          "Kendinize güzel bir güzellik maskesi hazırlayın.",
          "Yatmadan önce saçlarınızı güzelce yıkayın ve saç derinize masaj yaparak kendinizi rahatlatın.",
          "Bugün geçirdiğiniz günü derinlemesine düşünün , olumsuz şeyleri bir kenara bırakın , başarılarınıza odaklanın.",
          "Bugün yatağınıza 1 saat erken girin ve güzel , sağlıklı bir uyku çekin.",
          "Hayatınızı olumsuz etkileyen ne varsa aklınızdan silin ve herşeyin iyi olacağına inanın , inanmak başarmanın yarısıdır diye boşuna dememişler."
        ]),
    Challange(
        challangesName: "Günlük Tutma/Finish",
        description:
            "Günlük tutma alışkanlığınızı geliştirmeye başlamanıza yardımcı olacak 21 günlük ipuçları.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Kendinizle gurur duyduğunuz bir zamanı yazın",
          "Bu yıl için 3 dileğin olsaydı ne dilerdin ?",
          "Şu anda aklında ne var ?",
          "Özlediğiniz bir şey veya biri hakkında yazın",
          "Bugün en çok neye değer verdiğini yaz.",
          "Hayatınızı düşündüğünüzde sizi mutlu eden bir an hakkında yazın.",
          "Bugün hayat dursaydı ne yapmayacağına pişman olurdun ?",
          "İnsanların sizi nasıl ve neden hatırlamasını istiyorsunuz ?",
          "Daha fazla sevgi göstermek için kendinizin hangi yönlerine ihtiyacınız var ?",
          "Mükemmel bir günün nasıl olmalı ?",
          "Bu yıl başarmak istediğiniz her şeyi yazın.",
          "Hayatında daha çok neye ihtiyacın var ?",
          "Korkmasaydınız yapacağınız şeylerin bir listesini yapın ve bunlar hayatınızı nasıl etkilerdi düşünün",
          "10 yaşındaki halinize nasıl bir tavsiye verirdiniz?",
          "Yarını nasıl daha iyi bir hale getirebilirsin ?",
          "Sizi tedirgin eden her şey hakkında yazın ve bunu nasıl değiştirebilirsiniz düşünüp bulduğunuz çözümleri not alın",
          "Bugün öğrendiğiniz bir şey nedir ?",
          "Üstesinden geldiğiniz geçmiş bir mücadeleniz hakkında yazın. Sizi nasıl daha güçlü yaptığını ifade edin",
          "Şu an dört gözle beklediğiniz şey nedir ?",
          "Size en çok neşe veren nedir ? Bunun için nasıl daha fazla zaman ayırabilirsiniz ?",
          "Hayatınızda eksik olan bir şey nedir ve bunu nasıl değiştirebilirsiniz ?"
        ]),
    Challange(
        challangesName: "İyimserlik mücadelesi/Finish",
        description:
            "iyimserlik, pozitif bir tavra sahip olmayı seçerek hayatınızı yaşamak üzerine bilinçli bir karardır. Olayların olumlu taraflarını görebilmek , canlandırır ve umut verir.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Günü düşünün.Oldukça iyi giden en az bir şeyi yazın.",
          "Sahip olduklarını takdir et / şükret. Sevdiklerine onları ne kadar sevdiğini söyle",
          "Bugün ve her zaman kendine iyi davran. Her şeyi yapabileceğini ve ilerlemenin zaman aldığını unutma.",
          "Dört gözle beklediğin şeylerin bir listesini yap.",
          "Bugün neşeli olmak için ne sebeplerin olduğunu düşün",
          "Kendini başkalarıyla karşılaştırma. Birisini bir konuda kıskanıyorsan arkana yaslan ve bunu nasıl başardıklarını düşün",
          "Bu yıl kendi başardıklarını düşünmeye zaman ayır.",
          "Bugün gördüğün her insanda iyilik ara",
          "İlham verici müzikler veya bir podcast dinle",
          "İstediğin her şeyi başarabileceğini bilerek gelecek için en önemli önceliklerini ve planlarını yaz.",
          "Şimdide kal ve anın güzelliğinin keyfini çıkar, ağaçları ve bulutları izle hayatta olduğun ve sağlıklı olduğun için şükret.",
          "Bugün ve her zaman başardığın küçük-büyük zaferleri düşün ve kendinle gurur duy.",
          "Gerçekten zevk aldığın bir şey yaparak ruh halini değiştir",
          "Endişelendğin bir durum için , olabilecek en iyi senaryoyu yaz.",
          "Sorunlara değil çözümlere odaklan , bir liste yap ve sorunlarına çözüm odaklı yaklaş.",
          "Başkalarının beklentilerini bırak ve önemli olana odaklan",
          "Etrafını iyimse,pozitif,kibar insanlarla çevrele",
          "Yapamam yerine henüz yapamıyorum ama başaracağım de",
          "Kendine iyi bak , kendimizi iyi hissettiğimizde olaylara daha olumlu bakarız.",
          "Bir şeyden memnun değilsen şikayet etme , değiştir.",
          "Gelecekten umutlu olmak için üç iyi sebep bul"
        ]),
    Challange(
        challangesName: "Öz Bakım/Finish",
        description: "İşte evde iken kendin için yapabileceğin tam 21 şey.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "En sevdiğin TV dizisini izle.",
          "Günlük tut ve duygularını , deneyimlerini kaydet.",
          "Hoşuna giden bir hobi üzerinde çalış.",
          "Güzel bir kitap oku.",
          "Evde güzel bir egzersiz yap.",
          "Yeni birşeyler pişirmeyi öğren.",
          "Bir pasta veya tatlı yapmayı öğren.",
          "Kendi bulunduğun alanı temizle ve düzenle",
          "Arkadaşlarını ve aileni ara ",
          "Puzzle yap bu senin zihnini geliştirecek.",
          "Sanatla ilgilen, ve Pinterest'te güzel resimlere göz at",
          "Favori şarkılarını dinle",
          "Vücuduna güzel bir bakım yap",
          "Senin için özel birisine güzel bir mektup yaz.",
          "Kişisel gelişim dersi izle, youtube üzerinde çeşitli kanallar bulabilirsin.",
          "Güzel bir film izle ve anın tadını çıkar",
          "Bence birazcık şekerleme yapmaya ihtiyacın var.",
          "Sevdiğin bir konu ile ilgili güzel bir podcast dinle",
          "Meditasyon yap ve zihnini ve endişelerini dizginle",
          "Rahatlatıcı güzel bir banyo yap.",
          "Gelecek için hedeflerini belirle"
        ]),
    Challange(
        challangesName: "Düzenli olmak/Finish",
        description:
            "Unutma ki dağınıklıktan kurtulmak , organize olmanın ilk adımıdır.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Dolabını temizle.",
          "Kitaplarını düzenle.",
          "Yatak odanı organize et.",
          "Komidinini temizle.",
          "Kilerini organize et.",
          "Kullanılmayan kıyafetlerini ayıkla ve bağışla.",
          "Bilgisayarının içeriklerini düzenle.",
          "Buzdolabını temizle ve tüketim tarihi geçmiş yiyeceklerden kurtul.",
          "Varsa aracını,bisikletini veya kullandığın ve değer verdiğin bir eşyanı temizle.",
          "Eski gazete ve postaları gözden geçir.",
          "Donducurunu boşalt ve düzenle.",
          "Çalışma notlarını düzenle , çöp kutunu boşalt.",
          "Cüzdanını temizle.",
          "Mutfağını organize et.",
          "Masanızı veya çalışma alanınızı temizleyin.",
          "Kullanmadığın ayakkabılarından kurtul ve birisine bağışla.",
          "Temizlik malzemelerini düzenle.",
          "Şifonyerini organize et.",
          "Artık kullanmadığını uygulamaları kaldırın.",
          "İlaç dolabınızı temizleyin. Tarihi geçmiş ilaçları atın.",
          "Eski resimlerinizi düzenleyin ve anılarınıza sahip çıkın."
        ]),
    Challange(
        challangesName: "Yemek Pişirme/Finish",
        description:
            "Yemek yapmaktan keyif alıyor musunuz ? O zaman bu sizin için ideal bir egzersizdir. Burada yemeklerinizi çeşitlendirmek için 21 eğlenceli fikir bulacaksınız.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Yeni bir yemek tarifi deneyelim.",
          "Bir TV programı veya filmden esinlenerek bir atıştırmalık/yemek hazırla",
          "Bir Pinterest yemek tarifiyle yemek pişir.",
          "En sevdiğin kahvaltıyı hazırla.",
          "Yemeklerinde et yerine bezelye/mercimek/fasulye/nohut kullan.",
          "En sevdiğin yemeği pişir.",
          "En sevdiğin sosla/baharatla bir şeyler pişir.",
          "Meyve salatası yap.",
          "Renkli bir yemek pişirmeyi dene.",
          "Bugün öğünlerinde günlük meyve ve sebze porsiyonlarını arttır",
          "Her biri aynı harfle başlayan malzemelerle bir yemek pişir.",
          "Bir ikramlık pişir ve birine hediye et.",
          "Kendine özgü bir yemek yarat.",
          "Güzel bir pasta yap ve komşuna ikram et.",
          "Bugün içerisinde hayvansal ürün olmayan bir yemek pişirmeyi dene.",
          "Buzdolabında kalan artıklarla bir yemek pişir.",
          "En sevdiğin restorant  yemeklerinden birini evde hazırla.",
          "Başka bir ülkeden bir tarif hazırla.",
          "En sevdiğin içeceği evde hazırlamaya çalış.",
          "Değişik bir makarna yemeği pişir.",
          "Bugün bir şef ol ve en sevdiğin arkadaşlarına güzel bir yemek hazırla."
        ]),
    Challange(
        challangesName: "Kendinizi şımartın/Finish",
        description:
            "İşte kendinizi yenilemek ve içinizdeki cevheri açığa çıkarmak için günlük hayatınızda uygulayabileceğiniz 21 kişisel bakım önerisi",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Bir mum yakın, rahatlatıcı yavaş bir müzik açın ve güzel bir banyo yapın.",
          "Açık havada oturun , gün batımı veya gün doğumunu izlemek ve temiz bir hava almak size çok iyi gelecek.",
          "Kendinizi lezzetli bir dondurma ile şımartın.",
          "Yüzünüze güzel bir maske yaptırın.",
          "En sevdiğiniz yemeği pişirin.",
          "Kendinize manikür ve pedikür yaptırın.",
          "Vücudunuzdaki ölü ciltlerden kurtulun.",
          "Pizza sipariş edin ve en sevdiğiniz dizinin bölümlerini art arda izleyin",
          "Yüzünüzü ve vücudunuzu nemlendirin.",
          "Günde iki kez diş ipi kullanmak için zaman ayırın.",
          "Hayattaki başarılarınızın bir listesini yapın ve kendinizi kötü hissettiğinizde o listeye bakın.",
          "Bir fincan çay veya sıcak çikolata için.",
          "Saç maskesi yaptırın.",
          "Günlük tutun ve kendinize her daim şükredeceklerinizin bir listesini yapın.",
          "Eski bir arkadaşınıza mesaj atın ve onunla iletişim kurun.",
          "Romantik bir film izleyin ve hayatınızda birisi var ise ona güzel bir mesaj atın , yok ise aşkı bulacağınıza tüm kalbinizle inanın",
          "Sağlıklı ve lezzetli bir tatlı ile kendinizi şımartın.",
          "Resim yapın , hayal edin ve bir hikaye yazın , yaratıcı bir ruha sahip olduğunuzu unutmayın ! ",
          "En sevdiğiniz dizinin bölümlerini aileniz ile birlikte izleyin.",
          "Mevsimsel atıştırmalık hazırlayın.",
          "Güçlü yönlerinizi bir kağıda yazın ve bunlarla gurur duyun."
        ]),
    Challange(
        challangesName: "İyilik/Finish",
        description:
            "Her şeyin her an olabileceği bir dünyada nazik biri olun. Burada her gün yaşamınıza katabileceğiniz 21 nezaket eylemi bulacaksınız.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Bugün birine desteğinizi gösterin.",
          "Hayatınızda etkisi olan birine teşekkür notu yazın.",
          "En sevdiğiniz restoran/kafeye olumlu bir yorum bırakın.",
          "Bir aile üyesine veya sevdiğinize yatakta kahvaltı hazırlayın.",
          "Birinin sırada önünüze geçmesine izin verin.",
          "Birini bir hediye ya da sizin pişirdiğiniz bir şeyle şaşırtın",
          "Favori uygulamanıza güzel olumlu bir yorum bırakın.",
          "Aynalara pozitif yapışkan notlar koyun ve kendinizi mutlu edin.",
          "Birine güzel bir iltifat edin.",
          "Birini sevmenizin nedenlerinin bir listesini çıkarıp ona verin.",
          "Birine bahşiş verin.",
          "Günü sadece insanlar hakkında olumlu şeyler söyleyerek geçirin.",
          "Sevdiğiniz birine onu ne kadar takdir ettiğinizi söyleyin.",
          "Normalde yapmayacağınız bir iş yapın.",
          "Tanımadığınız en az 3 kişiye iyi günler deyin.",
          "Evsiz bir kişiye yemek ısmarlayın.",
          "Sizden beklenmeden birine yardım edin.",
          "Kurabiye pişirin ve birisine ikram edin.",
          "Yerel bir hayır kurumuna kıyafet / kitap / oyuncak bağışlayın.",
          "Bir süredir konuşmadığınız birisini arayın.",
          "Eğer durumunuz el veriyorsa , markette başkasının aldıklarını siz ödeyin."
        ]),
    Challange(
        challangesName: "Olumlu ifadeler/Finish",
        description:
            "Olumlu ifadeler kullanmak , kendinizi daha güvende hissetmenize ve olumlu hisleri arttırmanıza yardımcı olabilir. Güne başlamanın harika bir yolu olumlu düşünmektir.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "İçin de dışın da ayrı güzel , bunu sakın unutma.",
          "Duyguları göstermek sağlıklı ve iyidir.",
          "Sevmeye ve sevilmeye layıksınız.",
          "Güçlüsünüz ve kendinizle gurur duyuyorsunuz.",
          "Hedeflerinize ve hayallerinize inanın",
          "Bugün harika bir gün olacak !",
          "Kontrol edemeyeceğiniz şeyler için endişelenmeyeceksiniz.",
          "Çevrenizde sonsuz fırsatlar var.",
          "Bugün olumlu düşünmeyi seçin.",
          "Herhangi bir hedefe ulaşabilirsiniz.",
          "Unutmayın her şeyin bir nedeni vardır.",
          "Kendi güzel tarzınızla benzersiz ve farklısınız.",
          "Güveni soluyup korkuyu içinizden atıyorsunuz.",
          "Kötü bir gün geçirebilirsiniz ama unutmayın her şey geçicidir.",
          "Tam olarak olmanız gereken yerdesiniz ve ilerlemeye devam ediyorsunuz.",
          "Küçük adımlar da ilerlemektir, büyük işler zaman alır.",
          "Geçmişinizle barışıksınız.",
          "Zorlukların üstesinden gelme yeteneğiniz sınırsız ve başarılı olma potansiyeliniz sonsuzdur.",
          "Başardıklarınızla gurur duyuyorsunuz.",
          "Çevrenizdekilere ilham veriyorsunuz.",
          "Hayat ne olursa olsun yaşamaya değer !"
        ]),
    Challange(
        challangesName: "Evde egzersiz/eksik",
        description:
            "Acele etmeyin , 21 gün boyunca evinizde yapacağınız egzersiz planınız hazır !",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "İlk olarak 10 dk ısının ve 20 squat , 10 şınav , 30 saniye plank yapın.",
          "15 squat , 15 diz çekme , 20x4 ip atlama , 20 saniye duvarda oturma pozisyonu alın",
          "15 şınav , 15 squat , 20 diz çekme",
          "30 saniye plank , 20 şınav , 15 squat",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          ""
        ]),
    Challange(
        challangesName: "Verimlilik/Finish",
        description:
            "Bu mücadele sizi 21 gün boyunca her gün uygulamanız için tek bir verimlilik görevine teşvik edecek.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Uyandıktan sonra yatağınızı yapın , böylece yatağa geri dönmek cazip bir durum olmayacak.",
          "Güzel , sağlıklı ve enerjik bir kahvaltı yapın.",
          "Dağınık bir alanı düzenleyin, bu daha üretken hissetmenizi sağlayacak.",
          "Telefonda daha az zaman harcayın ve daha üretken olun.",
          "Kendinize bu haftanın planını yapın ve haftalık hedefler belirleyin.",
          "Telefonda sizi rahatsız eden bildirimleri kaldırın.",
          "Tüm hafta boyunca bir yemek planı oluşturun. Böylece her gün bunu düşünmek için zaman harcamanıza gerek kalmayacak.",
          "Yapılacaklar listesi oluşturun ve tüm görevleri tamamlamaya çalışın.",
          "30 dakika yürüyüşe çıkın , biraz temiz hava almak çok iyi gelecek.",
          "Gereksiz e-postalarınızı temizleyin ve istenmediğiniz sitelerde üyeliğinizi sonlandırın.",
          "30 dakika boyunca egzersiz yapın gün boyunca hiçbir şey yapmasanız bile , antrenmandan sonra çok iyi hissedeceksiniz.",
          "Yatmadan önce kitabınızdan bir bölüm okuyun.",
          "TV izlemeyin böylece kendiniz için ayıracak daha fazla zamanınız olacak.",
          "Dolabınızı düzenleyin ve artık istemediğiniz her şeyi bağışlayın.",
          "En sevdiğiniz şarkılarla bir çalma listesi oluşturun ve hiç kimse sizi izlemiyormuşçasına dans edin.",
          "Uyandıktan hemen sonra telefonunuzu kontrol etmeyin.",
          "10 dakika meditasyon yapın kendinizi yenilenmiş hissedeceksiniz.",
          "Kiler ve buzdolabınızı düzenleyin böylece en sevdiğiniz atıştırmalıkları aramak için çok fazla zaman harcamazsınız.",
          "Odanızı derinlemesine temizleyin ",
          "Artık size neşe getirmeyen insanları takipten çıkın. Kendinizi rahatlamış hissedeceksiniz.",
          "Bu yıl başarmak istediklerinizi bir kağıda yazın ve neler yapmalısınız madde madde belirleyin."
        ]),
    Challange(
        challangesName: "Abur cubura son/Finish",
        description:
            "Sağlıklı bir yaşam tarzı için küçük adımlarla başlayın ve bu 21 gün boyunca tüm abur cuburlardan kurtulun.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Bugün yemeklerinize daha fazla sebze eklemeye çalışın.",
          "Bugün çikolata yemeyin ve enerji elde etmek için fındık tercih edin.",
          "Beyaz ekmek yemeyin sadece bir tane tam tahıllı ekmek yiyebilirsiniz!",
          "Kurabiye veya kek yemeyin meyve ile değiştirin çok daha iyi değil mi ?",
          "Makarna yemeyin.",
          "Alkol tüketmeyin.",
          "Patates cipsi yemeyin.",
          "Gazlı içecek içmeyin su bugün için en iyi arkadaşınız olsun.",
          "Fast food yemeyin evinizde her zaman sağlıklı bir burger yapabilirsiniz.",
          "İşlenmiş et yemeyin daha fazla balık yiyin veya vejetaryen deneyin.",
          "Bütün gün vegan olmaya çalışın söylendiğinden daha kolay olduğunu göreceksiniz.",
          "Şeker yemeyin biraz hurma yiyin , doğal bir şekerdir.",
          "Patatesleri tatlı patateslerle değiştirin.",
          "Bugün iki litre su için.",
          "Rafine şeker kullanmayın.",
          "Bugün süt ürünleri de kullanmayın.",
          "Çokça meyve yiyin lezzetli ve en iyi doğal şeker meyvedir.",
          "Daha fazla yeşil yiyin. Brokoli bugün arkadaşınız olsun.",
          "Kahvaltıda yulaf ezmesi yiyin , lezzetlidir ve sizi saatlerce tok tutar.",
          "Bugün et yemeyin.",
          "Bütün görevleri tamamladınız , ödül olarak küçük bir parça biter'i hak ettiniz."
        ]),
    Challange(
        challangesName: "Sosyal Medya Detoksu/Finish",
        description:
            "Bu 21 küçük adım , internetten kopmanın ne kadar güzel olduğunu farketmenizi sağlayacak.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Bugün için 1 saatlik sosyal medya izni",
          "18.00'e kadar Instagram yok",
          "Yemek sırasında telefonunuzu kullanmayın.",
          "13.00'e kadarmesaj atmayın erkek veya kız arkadaşınız bekleyebilir.",
          "Bugün facebook yok. Messenger kullanabilirsiniz.",
          "Bugün sosyal medyada güncelleme yapmak yok. Kimsenin sizin ne yaptığınızı veya nerede olduğunuzu bilmesine gerek yok.",
          "Twittersız bir güne merhaba deyin, bir gazete açıp okuyun.",
          "Akşam 9'a kadar sosyal medya yok.",
          "Bugün sosyal medyayı hiç kullanmayın.",
          "Bugün için 30 dakika sosyal medya izni.",
          "Instagramsız bir güne merhaba deyin",
          "Dizüstü bilgisayarınızı 19.00 ' a kadar yapacak bir işiniz yoksa kapatın.",
          "Telefonunuzu evde bırakın.",
          "Faebook ve Messenger bugün tamamen yasak.",
          "Bugün için 20 dakika sosyal medya izni.",
          "Gün boyunca mesajlaşmak yok birini özlüyorsanız aramayı deneyin.",
          "Dizüstü bilgisayarsız bir gün geçirin, ara ara onun da dinlenmeye ihtiyacı var :)",
          "Saat 12'ye kadar telefon kullanmayın ve verimli bir sabah geçirin.",
          "20.00'den sonra sosyal medyayı kullanmayın böylece erken uyuyabilirsiniz.",
          "Bugün için Yotuube yok.",
          "Bugün telefonunuz olmadan egzersizinizi yapın , umarım bu 21 günlük alıştırma size teknolojiden uzak bir hayatın kıymetini gözler önüne sermiştir."
        ]),
    Challange(
        challangesName: "Pozitif Düşünme/Finish",
        description:
            "Düşünme şeklinizi değiştirmek, hayatınızda istediğiniz sonuçları elde etmenin anahtarı olabilir. Düşüncelerinize nasıl hakim olacağınızı öğrenirseniz , tüm dünyanız değişir.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Bugün gülümsemeyi dene , yabancılara gülümse , aynanın karşısında ve fırsat bulduğun her yerde gülümse. Kendini çok daha mutlu hissedeceksin.",
          "Bugün küçük şeylerin tadını çıkar.Birinin gülümsemesi , gün batımı , sabah kahven , güneşin sıcaklığı , gökyüzü..",
          "Hayatım korkunç diye düşünmek yerine şu anda işler pek iyi gitmiyor ama bu da geçecek daha iyi günler geliyor de !",
          "Olabilecek korkunç şeyleri düşünmektense, şu anda olabilecek harika şeyleri düşün.",
          "Pes ediyorum deme Zor da olsa denemeye devam edeceğim de.",
          "Başkalarının ne düşündüğünü umursamayı bırak. Başkalarının düşünceleri seni mutlu ve pozitif yapmayı amaçlamaz.",
          "Neden bunlar benim başıma geldi ? yerine bundan ne öğrenebilirim ? diye düşün.",
          "İyi şeylerin olacağına inan.",
          "Ben bunu yapamam diye düşünmek yerine bunu nasıl yapacağımı HENÜZ bilmiyorum ancak öğreneceğim de.",
          "Bugün kendini başkalarıyla kıyaslama. Bu tam bir zaman kaybıdır.",
          "Unutma , belirli bir olayı kontrol edemesen bile , kendi tepkini her daim kontrol edebilirsin.",
          "Meditasyon yap. Bu aşırı düşünmene engel olacak ve stresini azaltmana yardımcı olacak.",
          "Kendine olumlu şekilde konuşmayı dene. Ayna karşısında kendine olumlu ifadeler kullan.",
          "Güne uyandığın için şükret ve günü yine şükrederek bitir.",
          "Kendini sevdiğin ve seni seven insanlarla çevrele.",
          "Müzik dinle, müzik sağlığını ve gününü olumlu etkiler.",
          "Şu anda sahip olduğun her şeyi takdir et.",
          "Hayatın ne kadar kısa olduğunu ve seni üzen şeylerin sadece anı berbat ettiğini unutma , bu yüzden seni üzen şeylerden kurtul !",
          "Bugün senin için en değerli kişilerle iletişime geç onlara hayatlarının nasıl gittiğini sor , samimi sohbetler her zaman mutluluk verir.",
          "Yaşam standartlarını her daim daha iyiye gideceğini düşünerek yatağından kalk ve çabala.",
          "Tebrikler 21 günlük pozitif düşünce mücadelesinin son günündesin , artık bunu alışkanlık haline getirdiğini düşünüyorum. Hayat ne olursa olsun yaşamaya değerdir. "
        ]),
    Challange(
        challangesName: "Sabah Rutini/Finish",
        description:
            "Bu bölümde , güne doğru bir başlangıç yapmanıza yardımcı olacak 21 sabah alışkanlığını paylaşacağız.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Sabahları kendini iyi hissetmek için en sevdiğin müzik listesini dinle.",
          "Güzelce vücudunu esnet ve güneşin tenine dokunmasına izin ver.",
          "Kendine sağlıklı , lezzetli ve enerjik bir kahvaltı hazırla.",
          "Bugün için bir yapılacaklar listesi yap.",
          "Ailen ve arkadaşlarınla irtibat kur veya sevdiğin birine güzel bir günaydın mesajı gönder.",
          "Günlük tut, resim yap , bir enstrüman çal.. Yaratıcılığını besleyen bir şey yap.",
          "Kendin hakkında gurur duyduğun 5 şey yaz.",
          "15 dakika meditasyon yaparak güne güzel bir başlangıç yap.",
          "Kahvaltıdan önce bir bardak su iç.",
          "Pencerelerini temiz hava almak için aç , içeri biraz güneş ışığı girsin.",
          "Yürüyüşe çık veya evde egzersiz yap.",
          "En sevdiğiniz kitaptan bir bölüm okuyun.",
          "15 dakika yoga yap.",
          "Çıkmaya hazırlanırken bir podcast veya sesli kitap dinle.",
          "Dışarı çık ve taze sabah havasını solu.",
          "Gün içinde yapılacak 3 önemli şeyi belirle ve bunları gerçekleştir.",
          "Güzelce dişlerini fırçala ve bakımını yap.",
          "Egzersizini yap ve ılık bir duş al.",
          "Odanı güzelce düzenle ve bunu yaparken tempolu bir müzik aç.",
          "Uyanır uyanmaz telefona bakma !",
          "Her gün yapacaklarını ajandana not al ve İŞE KOYUL !"
        ]),
    Challange(
        challangesName: "Yeni Yıl , Yeni Siz/Finish",
        description:
            "Önümüzdeki birkaç ay güzel bir dönüşüm dönemi olsun. Yeni başlangıçların sihrine güvenin.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Olumlu bir sözün çıktısını alın ve cüzdanınıza veya aynanıza koyun, böylece her gün görebilirsiniz.",
          "İnsanlara sizin için ne kadar önemli olduklarını söyleyin.",
          "Olumlu düşünün ! Düşündüğünüz her senarya için , olabilecek en iyi şeyi hayal edin.",
          "Yeni bir şey deneyin. Yeni bir tarif,yeni bir televizyon dizisi,yeni bir restoran gibi... siz karar verin.",
          "Yürüyüşe çıkın ve etrafınızdaki dünyaya hayran kalın. Mümkün olduğunca temiz hava alın.",
          "Bugün için yapılacaklar listesi hazırlayın. Ve bunu hayatınızda yeni bir alışkanlık haline getirmeye çalışın.",
          "Mümkünse normalden bir saat önce yatağa gidin. Her gün sekiz saat uyumaya çalışın.",
          "Boş vaktiniz oldukça , üç tam derin nefes alın.",
          "Bugün en sevdiğiniz rengi giyin.",
          "Gün için bir sosyal medya molası verin ve sevdiğiniz biriyle kaliteli zaman geçirin.",
          "Yavaşlayın. Her şey yoluna girecek. Outurn ve bugün gün batımını izleyin.",
          "Birisi için güzel bir şey yapın.",
          "Bugün yanından geçtiğiniz herkese gülümseyin. Bu size yakışacak :)",
          "Bugün sağlıklı bir kahvaltı için zaman ayırın.",
          "Rahatlatıcı ,uzun bir banyo yapın. Kendinizi gerçekten rahat hissettiren bir şey yapın.",
          "Yatmadan önce meditasyon veya biraz esneme yapın.",
          "Sizin için özel birini arayın.",
          "Gün içinde olumsuz bir düşünceye yer yok. 3.Günde ne dendiğini hatırlayın.",
          "Evinizi ve çalışma alanınızı temizleyin ve düzenleyin.",
          "Hayatınızda en değer verdiğiniz insanları arayın ve kendinizi onlara hatırlatın.",
          "Her yeni günün değerini bilin ve gününüzü doyasıya yaşayın."
        ]),
    Challange(
        challangesName: "Güven/Finish",
        description:
            "Güven , sizin yarattığınız bir şeydir. Her şeyi başarabileceğinize dair bir kesinlik hissidir. Burada kendinize daha fazla güvenmenin 21 yolunu bulacaksınız.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Kendinizi güvensiz hissetmenize neden olan tüm sosyal medya hesaplarını takip etmeyi bırakın.",
          "Bugün ve bundan böyle iltifatları reddetmek yerine onları kabul etmeye çalışın.",
          "Duruşunuz konusunda farkındalık kazanın. Bütün gün dik durun.",
          "Çocukken yapmayı sevdiğiniz bir şey yapın.",
          "Bugün zorlayıcı bir şey yapın,rahat olduğumuzda büyüyemediğimizi unutmayın.",
          "Kendiniz hakkında sevdiğiniz 10 şeyi yüksek sesle söyleyin.",
          "Normalde yapmayacağınız bir şeye evet deyin.",
          "Yeni bir sağlıklı alışkanlık edinin (uygulamadan başka bir alışkanlığa başlayabilirsiniz)",
          "Söyleyecek bir şeyiniz olduğunda KONUŞUN !",
          "İstemediklerinizden çok ne istediğinize odaklanın.",
          "Yapmayı sevdiğiniz veya yapmaya başlamak istediğiniz bir şey üzerinde becerilerinizi geliştirmek için çalışın.",
          "Başarılarınızın bir listesini çıkarın ve gelecekte bu listeye yeni eklemeler yapmaya devam edin.",
          "Hızlı bir egzersiz yapın , duş alın , hazırlanın ve kendinizi harika hissettirecek bir kıyafet giyin.",
          "Kendi başınıza dışarı çıkın sinemaya , alışverişe , gün batımını izlemeye gidin.",
          "Eski bir arkadaşınıza ulaşın.",
          "Her olumsuz düşünce için olumlu bir düşünce bulun.",
          "Birine iyi bir tavsiye verin.",
          "Sevdiğiniz bir egzersizi yapın.",
          "Küçük şeyler üzerinde çalışın. Küçük küçük başarılar kendinizi iyi hissetmenizi sağlar.",
          "Bugün kendi iç sesinize kulak verin ve yapmak istediklerini düşünün ve bunları gerçekleştirebilecek güçte olduğunuza inanın.",
          "Hayatınızdaki insanlara ve en önemlisi kendinize güven vermeye devam edin !"
        ]),
    Challange(
        challangesName: "Çiftler için Alışkanlıklar/Finish",
        description:
            "Kelimeler olmadan 'Seni Seviyorum' demenin 21 yolu. Bu meydan okumalar , sağlam bir ilişki kurmanıza ve sevgilinize karşı daha sevecen , nazik ve düşünceli olmanıza yardımcı olacaktır.",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Partnerinizle ilgili sevdiğiniz şeylerin bir listesini yapın.",
          "Sürpriz bir buluşma gecesi planlayın.",
          "Partnerinize beklenmedik bir zamanda onu sevdiğinizi söyleyin.",
          "İlişkiniz hakkında sahip olduğunuz bir korkuyu paylaşın.",
          "Partnerinizle ilgili iyi bir anınızı paylaşın.",
          "Partnerinize romantik bir sabah mesajı/sesli mesaj gönderin.",
          "Partnerinize bugün bir şey için teşekkür edin.",
          "Partnerinizi harika bir şeyle şaşırtın.",
          "İlişkiniz için sahip olduğunuz bir hedefi paylaşın.",
          "Partnerinize bir iltifat edin.",
          "Bir hafta sonu kaçamağı planlayın.",
          "Eski resimlere birlikte bakın.",
          "İlk tanıştığınız zamanı hatırlayın.",
          "Birlikte bir yapılacaklar listesi oluşturun.",
          "Rastgele bir kelime seçin ve partnerinizle koyu bir sohbet başlatın.",
          "Birlikte bir bulmaca yapın.",
          "Partnerinizle bir aşk mektubu yazın ve daha sonra bulması için saklayın.",
          "Partnerinizin birlikte yapmaktan hoşlandığı bir şey yapın.",
          "En sevdikleri yemekleri yapın.",
          "Partnerinize güzel bir sabah kahvaltısı hazırlayın.",
          "Biraz erken kalkıp partnerinizi uyurken izleyin."
        ]),
    Challange(
        challangesName: "Çalışma Zorluğu/Finish",
        description: "Stres gerçektir, ertelemek de öyledir. 21 gün içinde nasıl etkili bir şekilde çalışacağınız öğrenmeye hazır mısınız ? ",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Bir program yapın ve her zaman not alın.",
          "Notlarınızı elle yazın ve anahtar kelimelerinizi işaretleyin.",
          "Bir seferde 30 dakika çalışın.",
          "Uykudan önce notlarınızı gözden geçirin.",
          "Bir zamanlayıcı kurun ve yalnızca tek bir göreve odaklanın.",
          "Birine öğretiyormuşsunuz gibi çalışın.",
          "Tüm görevleri tamamladığınız takdirde kendinize bir ödül sözü verin.",
          "Notlarınızda renkler ve fosforlu kalemler kullanın.",
          "Youtube üzeirinde anlamadığınız kelimeleri araştırın.",
          "Okurken sesinizi kaydedin.",
          "Kavramları özetleyin.",
          "Bugün birlikte çalışacağınız birini bulun.",
          "Bugün / bu hafta öğrendiklerinizi gözden geçirin.",
          "Daha iyi öğrenme için uygulamalar veya bilgi kartlarını kullanın.",
          "Görevlerinizi önceliklendirin, önce büyük görevleri tamamlayın.",
          "Bilgileri düzenlemek için zihin haritalarını kullanın.",
          "Dikkatinizin dağılmayacağı , sessiz bir çalışma yeri seçin.",
          "45 dakika bir şeye odaklanarak çalışın.",
          "Ödevinize/Görevinize başlamadan önce notlarınızı gözden geçirin.",
          "Hayatta başarmak istediklerinizi bir kağıda güzelce yazın ve bunları gerçekleştirmek için işe koyulun.",
          "Her gününüzü yatmadan önce mutlaka planlayın."
        ]),
    Challange(
        challangesName: "Zihin Sağlığı/Finish",
        description: "Kendinize zaman ayırmak , beden ve ruhunuzu dinlemek sağlığınız için çok önemlidir. Lisanslı terapistler lmasak da , sağlıklı bir zihin gelişimi için işte size birkaç ipucu",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "Olumsuz paylaşımlar yapan sosyal medya hesaplarını hemen takipten çıkarın. Eğlendiren,eğitici olan hesapları takibe al.",
          "Uyumadan önce , gün boyunca hoşunuza giden 3 şeyi yazın.",
          "Fırsat buldukça , 3 kere derin derin nefes alın.",
          "Farkındalığı alışkanlık haline getirin. Anı yaşayın.",
          "Bir süredir konuşmadığınız sevdiğiniz birini arayın.",
          "Bir günlüğüne sosyal medyaya ara verin ve çevrenizdeki yaşama odaklanın.",
          "Kafanızda olan biten her şeyi sadece bir kağıda yazın ve gereksizlerin üzerini çizin.",
          "Bir şeyi beklerken hayatınızın en iyi anlarını düşünün.",
          "Bir rehber eşliğinde meditasyon yapın.",
          "İçinizdekileri yüksek sesle söyleyin ve içinizi dökün.",
          "Bugün dinlenmeye ve rahatlamaya odaklanın ve erken yatın.",
          "Telefonunuza bakmadan çevrenize odaklanarak bir yürüyüşe çıkın.",
          "Endişeli hissettiğinizde , mutlu olduğunuz bir yeri hayal edin.",
          "Zihinsel sağlığınıza iyi gelecek bir şey okuyun veya izleyin.",
          "Hayalini kurduğunuz hayatı kafanızda canlandırın ve oraya ulaşmak için hangi adımları atmanız gerektiğini yazın.",
          "Olumlu içsel konuşmalar gerçekleştirin.",
          "Kendinize bir aşk mektubu yazın.",
          "Olumsuz düşüncelerin temelini keşfetmeye başlayın.",
          "Minnettar olduğunuz 5 şeyi yazın.",
          "Başkalarıyla kendinizi kıyaslamayı bırakın. Herkes aynı şartlar altında yaşamaz kıyaslanacak tek kişinin kendiniz olduğunun farkına varın.",
          "Sahip olmak istediğiniz en önemli 3 şeyi düşünün ve bunlara ulaşmak için nasıl bir yol izleyeceğinizi zihninizde canlandırın."
        ]),
    Challange(
        challangesName: "",
        description: "",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          ""
        ]),
    Challange(
        challangesName: "",
        description: "",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          ""
        ]),
    Challange(
        challangesName: "",
        description: "",
        imagePath: "assets/design_course/interFace1.png",
        days: [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          ""
        ]),
  ];
}
